# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=1)),
                ('pet', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('sleep_late', models.BooleanField(default=False)),
                ('rise_early', models.BooleanField(default=False)),
                ('neat', models.BooleanField(default=False)),
                ('friends', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=200)),
                ('budget', models.IntegerField(default=0)),
                ('dishes', models.BooleanField(default=False)),
                ('skimpy', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('drugs', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=1)),
                ('pet', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('sleep_late', models.BooleanField(default=False)),
                ('rise_early', models.BooleanField(default=False)),
                ('neat', models.BooleanField(default=False)),
                ('friends', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=200)),
                ('budget', models.IntegerField(default=0)),
                ('dishes', models.BooleanField(default=False)),
                ('skimpy', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('drugs', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='preferences',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributes',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
