# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
