# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171103_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
