# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20171103_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
