# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_dealbreakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealbreakers',
            name='budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealbreakers',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealbreakers',
            name='language',
            field=models.BooleanField(default=False),
        ),
    ]
